apiVersion: com.github.mosen.openshift-janitor/v1alpha1
kind: Sweep
metadata:
  name: example-sweep
spec:

  # The age of a project, after which the owner will be warned about its removal.
  warnAgeDays: 83

  # The maximum number of days old a Project can be before removal
  deleteAgeDays: 90

  # Ignore these projects/namespaces for deletion
  ignore:
    - mtm-cicd

  # Ignore projects with this annotation
  ignoreAnnotation:
    com.github.mosen.openshift-janitor: "ignore"
