apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: sweeps.com.github.mosen.openshift-janitor
spec:
  group: com.github.mosen.openshift-janitor
  names:
    kind: Sweep
    listKind: SweepList
    plural: sweeps
    singular: sweep
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      description: Sweep is the Schema for the sweeps API. A "Sweep" is a single operation
        which scans the entire cluster for outdated/unused Projects
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: SweepSpec defines the desired state of Sweep, which is a single
            scan of all Projects/Namespaces for Old and Unused Resources.
          properties:
            deleteAgeDays:
              minimum: 1
              type: integer
            ignore:
              items:
                type: string
              minItems: 1
              type: array
            ignoreAnnotation:
              additionalProperties:
                type: string
              type: object
            warnAgeDays:
              minimum: 1
              type: integer
          required:
          - deleteAgeDays
          - warnAgeDays
          type: object
        status:
          description: SweepStatus defines the state of a Sweep operation
          properties:
            active:
              type: boolean
            finished:
              format: date-time
              type: string
            projectsDeleted:
              items:
                type: string
              type: array
            started:
              format: date-time
              type: string
          required:
          - active
          type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
